(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.bg1 = function() {
	this.initialize(img.bg1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1456,180);


(lib.bg2 = function() {
	this.initialize(img.bg2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1456,230);


(lib.bg3 = function() {
	this.initialize(img.bg3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1456,180);


(lib.car1 = function() {
	this.initialize(img.car1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,449,246);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.sb_sc3bg = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(7,10,5,0)","rgba(42,74,21,0.259)","rgba(69,91,44,0)"],[0,0.478,1],-1220,-0.1,1219.9,-0.1).s().p("Ei+nAs/MAAAhZ9MF9PAAAMAAABZ9g");
	this.shape.setTransform(32.53,129.6851,0.4119,2.3538,11.6882);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#0C0F08","rgba(69,91,44,0)"],[0.325,1],-1220,-0.1,1219.9,-0.1).s().p("Ei+nAs/MAAAhZ9MF9PAAAMAAABZ9g");
	this.shape_1.setTransform(2540.198,289.4225,0.6639,2.3538,-168.3118);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#070A05","rgba(69,91,44,0)"],[0.145,1],-1220,-0.1,1219.9,-0.1).s().p("Ei+nAs/MAAAhZ9MF9PAAAMAAABZ9g");
	this.shape_2.setTransform(-1032.5434,111.2043,1.2015,2.3538,11.6882);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// bg3
	this.instance = new lib.bg3();
	this.instance.setTransform(-1902,0,2.7936,2.7936);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-2605.2,-849.2,6075.799999999999,1966.2);


(lib.sb_btnt = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_9
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhgBRQA5gEAmgRQgJgJgIgFIAOgNIAVASQAVgMAXgWIgtAAQggAUglANIgNgRQAjgKAXgNQAYgMAagYIAQAIQABABAAAAQABAAAAABQAAAAABABQAAAAAAABQAAADgHABIgOAKIAmAAIABgBQABAAAAAAQABAAAAAAQAAAAAAABQABAAAAAAIAMAJQABAAABABQAAAAAAAAQABABAAAAQAAABAAAAQAAAEgHABQgwArgiAPQgkARg+AHgAhdgCQAngEAbgLQgFgHgKgIIAOgMIAUARQARgLAUgVIguAAQgbATgfANIgMgQQAegKAQgLQAVgNATgVIAPAIQAAAAABABQAAAAABAAQAAABAAABQAAAAAAABQAAACgHABIgHAHIApAAIACgCIACABIANAKQAAAAABABQAAAAABAAQAAABAAAAQAAABAAAAQAAAEgGABQgnAogZANQgcAOgzAHg");
	this.shape.setTransform(122.775,9.975);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAXBSQgXgIgMgGIgJAGQgTANgpAIIgOgTQAhgDAVgKQAGgCAFgEQgPgLgJgMIARgJQAJALALAHQAFgJABgQIgtAAIAAALIgUAAIAAhZIBCAAIAAgRIhTAAIAAgRIC1AAIAAARIhQAAIAAARIBBAAIAABZIgTAAIAAgLIguAAQgBAVgGALIgBACQALAGAaAHQAbAGAgADIgOAVQghgGgagHgAAIACIAuAAIAAgOIguAAgAg4ACIAuAAIAAgOIguAAgAAIgcIAuAAIAAgQIguAAgAg4gcIAuAAIAAgQIguAAg");
	this.shape_1.setTransform(85.375,10.275);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgIBhIAAg2IhJAEQgCAEgCAAQgBAAAAAAQAAgBgBAAQAAAAAAgBQAAgBgBAAIgEgSIBOgDQgVgOgagNIANgMIAPAIIAXgZIANAHQAAABABAAQABAAAAAAQAAABABAAQAAAAAAABQAAACgEACIgVASIASAMIAngoIAPAJQAAAAABABQAAAAAAABQABAAAAABQAAAAAAABQAAACgEABIgqAiIAwgCIgMgMIAPgJQAZAZAJARIgRAIIgJgOIg6ADIAAA4gAAXA9IAPgKQAWARAlAMIgSAOQghgOgXgTgAhgBPQAlgJAYgTIANAJIACADQAAABAAAAQgBAAAAABQgBAAgBAAQAAABgBAAQghATgYAJgABMAAIAAggIiVAAIAAAgIgUAAIAAgvIBVAAIAAgOIhLAAIAAgQIBLAAIAAgTIAQABQAFABAAACQAAACgDADIAAAKIBJAAIAAAQIhJAAIAAAOIBVAAIAAAvg");
	this.shape_2.setTransform(47.525,9.925);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAZBjIAAhFQgIAQgIALQgMAQgTAQIgSgQQAVgNAPgQQAHgIAKgSIgmAAIAAgSIAyAAIAAgSIARABQAFABAAACQAAACgDADIAAAJIA1AAIAAASIgpAAQAKAWAIAKQAJAMARAMIgRAQQgPgNgIgPQgJgNgHgSIAABEgAheBPIAPAAQAIAAAAgJIAAguIgMAIQgEAGgCAAQgBAAAAAAQgBAAAAgBQAAAAgBgBQAAAAAAgBIgHgTQAQgHAMgGIAAgxIgbAAIAAgRIAbAAIAAgjIAUACQABAAABAAQAAABABAAQAAAAABABQAAAAAAABQAAACgFACIAAAaIAYAAIAAARIgYAAIAAApIAYgOIAAASIgYAOIAAA8QAAANgHAFQgFAGgWAAgAgYgSQAQgIAGgHQAEgGACgHQADgJABgQIAQACQABAAABABQAAAAABAAQAAAAABAAQAAABAAAAQAAACgDACQgCAPgDAJQgCAHgFAGQgGAKgQAJgABCgJQgMAAgGgHQgFgGAAgNIAAgjIAUADQAEABAAACQAAACgEADQgDACAAAEIAAANQAAAIACAEQACAEAIAAQAEAAADgDQACgDACgMIAQAIQgDARgFAEQgDAEgFAAgAgYg1IAAgoIB3AAIAAAnIgSAAIAAgWIhTAAIAAAXg");
	this.shape_3.setTransform(10.025,9.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},5).to({state:[]},1).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},2).wait(39));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,132.5,19.9);


(lib.mo_sc3tt = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAUCFQgigBgZgGQgZgHgMgNQgHgFgEgJIgZAfQgDAEgDAAQgDAAgBgDIgPgVQAXgPAQgPIAAg6IgVAAIAAgWIAxAAIAABTQAJARASAGQAUAIArAAQA8AAA6gEIgJAegAA/BHIAXgBQAJAAAAgKIAAgzIguAAIAAAbIAQgCIgGgQIATgGQAKAaAFAWIgVADIgCgKQgOADg6AKQgCAEgEAAQAAAAgBgBQAAAAAAAAQgBgBAAAAQAAgBAAgBIgFgXIAngEIAAgeIgtAAIAABRIgaAAIAAhlIBHAAIAAgSIg6AAIAAhiICMAAIAABiIg5AAIAAASIBIAAIAABOQgBAUgRAFQgOAFgOAAgAAxgyIAjAAIAAgSIgjAAgAgLgyIAjAAIAAgSIgjAAgAAxhXIAjAAIAAgUIgjAAgAgLhXIAjAAIAAgUIgjAAgAiHg8IASgSQAdANAVAOIgSASQgYgPgagMgAh5hxIATgTQAZANAUAPIgRATQgWgPgZgNg");
	this.shape.setTransform(509.5,13.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhaCEIAAiuIgqAAIAAgXIBqAAIAAAXIgnAAIAACugAghB+IAAgWIAqAAIgGgSIgUAAIAAg/ICIAAIAAA/IgZAAIgHASIAwAAIAAAWgAAhBoIAeAAIAGgSIgpAAgAAGBAIBZAAIAAgTIhZAAgAiHBgIAGgjQADgeABg0IAWACQAFABAAACQAAACgEACIgIBxgAg4AEIAAgaIAVAAIABAaQAAAlAJAtIgWACQgJgrAAgpgAgYAOIAAgVICbAAIAAAVgAgRgRIAAhcIApAAIAAgWIAUACQAHAAgBADQAAACgEADIAAAMIARAAIAAgVIAVACQAGABAAACQAAACgEADIAAALIApAAIAABcgABWgnIARAAIAAgOIgRAAgAAugnIARAAIAAgOIgRAAgAAGgnIASAAIAAgOIgSAAgABWhJIARAAIAAgOIgRAAgAAuhJIARAAIAAgOIgRAAgAAGhJIASAAIAAgOIgSAAgAh9hbIAAgXIBZAAIAAAXg");
	this.shape_1.setTransform(457.75,13.775);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AiFB2QAxgIAigOIg4AAIAAh1IDQAAIAAB1Ig4AAQAkAKA0AHIgVAXQg3gMgrgRIAKgLIg6AAIALAIQABABABAAQAAAAAAABQABAAAAABQAAAAAAABQAAACgFABQgwARgpAJgAhPBMICbAAIAAgPIibAAgAhPAsICbAAIAAgPIibAAgAhPALICbAAIAAgMIibAAgAiFghIAAgVIB3AAIAAgMIhhAAIAAg1IBhAAIAAgRIAXACQAHAAgBAEQABACgFAFIAAAEIBiAAIAAA1IhiAAIAAAMIB3AAIAAAVgAALhWIBHAAIAAgNIhHAAgAhVhWIBHAAIAAgNIhHAAg");
	this.shape_2.setTransform(406.3,13.925);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgEBuIAaAAQAPAAABgIIAAgUIhfAAQAWANATAQIgSARQgXgUgYgNIAOgNIhCAAIAAgXICrAAIAAgOIiNAAIAAh0IBGAAIACgQIhiAAIAAgYIBCAAIgMgNIAZgMIATAZIA8AAIARgZIAVALQAEADAAABQAAADgFADIgEAEIBBAAIAAAYIhdAAIAAAQIBFAAIAAB0IgnAAIAAAOIBGAAIAAAXIhGAAIAAAZQAAAPgLAHQgKAIgmAAgAhMAXICYAAIAAgMIiYAAgAhMgGICYAAIAAgNIgwAAQgRAAAAgMIAAgSIgbAAIgCAFQgKAUgaAMIgSgTQARgHALgLIggAAgAAigpQAAAEAGAAIAkAAIAAgMIgqAAgAgKhHIAVAAIAAgQIgTAAg");
	this.shape_3.setTransform(354.625,13.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgvBsIAbAAQAPAAAAgMIAAgNIh6AAIAAgXIB6AAIAAgVIAPACIAZgQIiJAAIAAgWICpAAIAGgDIAGADIANAIQABAAABABQAAAAABABQAAAAAAABQAAAAAAAAQAAAEgGAEIhFAhIAAAFIBsAAIAAAXIhsAAIAAARQAAARgLAIQgJAJgkAAgAhZgJIAAhBIC2AAIAABBgAg/geICBAAIAAgXIiBAAgAh/hWIAAgYIByAAIAAgXIAZACQAIABAAADQAAACgGAFIAAAKIByAAIAAAYg");
	this.shape_4.setTransform(302.775,13.85);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAdB/IAAj3IBjAAIAACvQAAAUgTAFQgOAFgOAAIgLgaIAWgBQAKAAAAgLIAAiPIgvAAIAADfgAh4BuIgHgdIAUgCIAAjNIB0AAIAACFIhaAAIAABDQAbgEAggKIgNgYIASgOQATAZAVAtIgYAQIgLgaQgfAKhEARQgDAHgDAAQgCAAgBgGgAhRgQIBAAAIAAggIhAAAgAhRhIIBAAAIAAgeIhAAAg");
	this.shape_5.setTransform(250.675,14.55);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAbBmIAUAAQALAAABgIIAAi1IhCAAIAAgaICSAAIAAAaIg1AAIAAC6QAAAPgJAIQgIAIgfAAgAh+CAIAAhlIBkAAIAABlIgZAAIAAgQIgxAAIAAAQgAhkBbIAxAAIAAgrIgxAAgAh4AIIAAgVIBaAAIAAAVgAh3geIAAgVIBZAAIAAAVgAiJhFIAAgYIB5AAIAAAYgAh2hrIAAgWIBXAAIAAAWg");
	this.shape_6.setTransform(167.75,14.15);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("ABdCKIAAgHIhPAAIAAAHIgYAAIAAg0QgIARgRAYIgYgLQAVgaAIgVQALgeAAgcIAAg0ICCAAIAABZIhvAAIgBANIB4AAIAABNgAAOBuIBPAAIAAgcIhPAAgAADAcIBSAAIAAgQIhRAAgAAEgGIBRAAIAAgOIhRAAgAiABuIAUAAQALAAABgMIAAhBIgVAMQgEAIgDAAQgCAAgCgFIgIgXIAogRIAAhHIgkAAIAAgYIAkAAIAAguIAcAEQAFABAAADQAAADgIAEIAAAfIAgAAIAAAYIggAAIAAA6IAhgSIAAAXIghATIAABTQAAARgIAIQgJAJgeAAgAgwg1QAfgSASgSQASgRASgfIAYAHQADACAAADQAAACgIABIAAABQASAYASALQAPAMAeANIgWATQgVgKgNgMIAAAMIhLAAIAAgLQgRAPgPAIgAAThKIgCACIA2AAQgOgNgNgSQgKANgPAQg");
	this.shape_7.setTransform(115.825,13.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAUBsIAbAAQAPAAAAgIIAAg4IhfAAIAAgYIBfAAIAAgdIhYAAIAAgZIA4AAIAAglIg/AAIAAgXIA/AAIAAgnIAYADQAGABAAADQAAACgEAEIAAAaIBHAAIAAAXIhHAAIAAAlIBAAAIAAAZIggAAIAAAdIAqAAIAAAYIgqAAIAAA9QAAAOgLAHQgKAHglAAgAiBBqIAAjUIBVAAIAADHIgaAAIAAgPIghAAIAAAcgAhnA2IAhAAIAAg3IghAAgAhngWIAhAAIAAg8IghAAgAgUBJIASgRQAMAJAUASIgUASQgNgQgRgMg");
	this.shape_8.setTransform(64.675,13.65);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AiECFIAAkFIBMAAQAAgBABgBQAAAAAAgBQABAAAAgBQAAAAABAAIAWASIgkBMQAeAgAAAbQAAAdgPASQgQARgZAAIgKgaQAagEAHgKQAIgJAAgRQAAgVgfgiIAdhFIgqAAIAADugAgsB+IgFgaIAagFIAAjeICBAAIAAB3IgvAAQAFAYAIASQAQgLAUgUIASASQABAAAAABQABAAAAABQAAAAAAABQAAAAAAABQAAACgIAAQgSAOgTANQAPAaAjAbIgbAVQgUgVgPgWQgOgWgJgXQgIgTgFgdIghAAIAABhQAcgGAWgIIAAAWQgYAJg+AUQgDAEgDAAQgDAAgBgEgAACgeIBOAAIAAgbIhOAAgAAChPIBOAAIAAgaIhOAAg");
	this.shape_9.setTransform(13.275,14.325);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.mo_sc3tt, new cjs.Rectangle(0,0,523.3,27.6), null);


(lib.Path = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#333A2B").s().p("AuxDFIAAmJIdjAAIAAGJg");
	this.shape.setTransform(94.6,19.725);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Path, new cjs.Rectangle(0,0,189.2,39.5), null);


(lib.sb_sc2title = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E18E4E").s().p("AAVCmIAAjkIgGAAQgVAogXAZQgPgRgXgSQAWgXAUgjQATgjALgmIAxAMQgHAVgJAVICDAAIAAAvIhfAAIAAAeIBWAAIAAAtIhWAAIAAAgIBaAAIAAAvIhaAAIAABKgAh+CmIAAimIgPARQgDgLgJgQQgJgTgGgIQAXgXAUgjQAVgiAMgkIAyAQQgOAkgSAjIAAD0g");
	this.shape.setTransform(214.525,17.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#E18E4E").s().p("AioCKQATgWAKgSQAKgQAJgZIA7ABQAFAJAHAIQAfgXAfgjQAhggAZgjIjUAAIAAgyIBxAAIgdgsIAugZQAeAqARAbIBEAAIALgCIAnAYQgdAygtAyQgqAvgqAjQAgAKAxAAIBcgBQgMAUgFAeIhOAAQg4AAgigLQgqgNgagfQgRAjgRAag");
	this.shape_1.setTransform(174.5,16.95);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#E18E4E").s().p("ABgCbIiuAGQgnACgLAEIAAAAIAAAAIAAgBQgEgRgJgXIAUgHIALgEIgxAAIAAgcIE8AAIAAAcIg4AAQAZAOAUARIgjAVIgPgMgAg8CDIBzgEIgQgIIAIgEIhQAAQgOAJgNAHgAhyBPIAAgbIDnAAIAAAbgAAAAiIAAAIIibAJIgBgcIA6gBIAAgJIgqAAIAAgPIgGACIgRgUQAUgIAWgOIghAAIAAgZIA4AAIAAgHIgoAAIAAgYIAoAAIAAgHIAqAAIAAAHIAqAAIAAAYIgqAAIAAAHIA5AAIAAAZIggAAQASAIANAHIAQgVIgLAAIAAgjIAiAAIAAgUIAlAAIAAAUIA1AAQgCBcAIAAQADAAABggQANARAMAHQgDAYgGAKQgIALgQAAQgbAAgJgnIgCgIIgSAYIgSgNQgPAZgaAQQgHgIgJgJgAg4AUIA3gCQAOgMAJgPIgWgKIgLASIgCgCIAAAQIgrAAgAg4gJIAhAAQgOgJgTgIgAh6gJIAYAAIAAgMIgYAMgABHgYIAVANIgDglIgOAAQgBAMgDAMgAhWgcIgDABIAgAAIgFgCIAJgNIgvAAgAAkgpIABgHIgTAAIASAHgAAfhqIAAgIIgZAAIAAgjIAZAAIAAgRIAzAAIAAARIBLAAIAAAjIhLAAIAAAIgAhThqIAAgIIhKAAIAAgjIBKAAIAAgRIAyAAIAAARIAeAAIAAAjIgeAAIAAAIg");
	this.shape_2.setTransform(134.7,17.275);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#E18E4E").s().p("AihCKIAAgzICDAAIAAiqIhvAAIAAg2IEaAAIAAA2IhyAAIAACqICHAAIAAAzg");
	this.shape_3.setTransform(94.7,17.85);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#E18E4E").s().p("AgKCiQglAAgOgOQgNgOAAgmIAAidIA1AAIAACdQAAANADADQADADALAAIAoAAQAMAAAEgLQADgMACgnQASANAeAIQgEAzgNASQgNAUgjgBgAinBgQAUhAAFhMIAzAKQgLBrgMArgABkAgQgLgmgOgfIAwgTQAOAfANAjQAMAkAGAcIg0AWQgEgbgMglgAhAh+IAigkQBGArAdAcIgnAoQgdgghBgrg");
	this.shape_4.setTransform(54.9,16.95);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#E18E4E").s().p("AiYCeIAAk7IEoAAIAAAxIj1AAIAADJID+AAIAAAwIj+AAIAAARgAhaBQIAAgvIBTAAIAAhRIhMAAIAAguIDNAAIAAAuIhQAAIAABRIBiAAIAAAvg");
	this.shape_5.setTransform(15.325,18.125);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,231.5,34);


(lib.sb_sc2tbg = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_4
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(51,58,43,0)","#333A2B","rgba(51,58,43,0)"],[0,0.502,1],-300,0,300,0).s().p("Egu3AHMIAAuXMBdvAAAIAAOXg");
	this.shape.setTransform(300,46.025);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,600,92.1);


(lib.sb_sc2if = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AA3BiIgXgJQgNgFgHgGQgIgGgJgLIgIAKQgJAJgNAHQgOAIgQAFIgaAHQgEgBgBgCIgHgIIgBgDIABgBQARgCAQgGQASgEAMgIQAIgFAJgHIhVAAQgDAAAAgFIAAgHQAAAAABgBQAAgBAAAAQABgBAAAAQABAAAAAAIBeAAIABgDQAEgHAAgMQAAgBABAAQAAgBAAAAQABAAAAAAQABgBABAAIAQADIACACIgCACQgEACAAADIgEANIApAAIgMgGIgLgEQAAgCAIgIIACgCIAPAGIAMAHIgBABIgGAIIA3AAQABAAABAAQAAAAABABQAAAAAAABQABABAAAAIAAAHQAAAFgEAAIhdAAIAJAHQAGAEAOAHQAFACARAGIAmAHIABAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAIgIAJQAAAAAAAAQgBABAAAAQgBAAAAAAQgBAAAAAAQgUgDgQgGgAhtASIAIgDQAGgEACgDQADgEADgHIACgOIgPAAQAAAAgBAAQAAAAAAgBQAAAAAAgBQgBAAAAgBIAAgHQAAgBABgBQAAAAAAgBQAAAAAAAAQABAAAAAAIA0AAIAAgWIghAAIAAAHQAAADgEAAIgJAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAgyQAAAAAAAAQAAgBABAAQAAAAABAAQAAgBABAAQASAAAAAEQAAAAgBAAQAAABAAAAQAAABgBAAQAAAAAAABQgBAAAAAAQgBAAAAAAQAAABAAABQgBAAAAABIAAAXIAhAAIAAglQAAgBAAAAQAAAAABgBQAAAAABAAQAAAAABAAQARAAAAADQAAABAAAAQAAABAAAAQgBABAAAAQAAAAgBAAQAAAAgBAAQAAABAAAAQAAABAAAAQAAABAAABIAAB3QAAACgFAAIgJAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAgBAAAAIAAgrIgVAAIgDARQgBAJgEAGQgFAGgDACQgEADgIADgAAwAXQAAAAgBAAQAAgBAAAAQAAAAAAgBQAAgBAAgBIgFgKQAAAAAAAAQAAgBABAAQAAAAAAAAQABAAAAAAQAIABAHAAQAKABAAgIIAAgPIhYAAQAAAAgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBIAAgHQAAgBAAAAQAAgBABAAQAAAAAAAAQABgBAAAAIBYAAIgBgUQAAgBABAAQAAAAAAAAQABAAAAAAQABAAABAAIATACQAAAAABABQAAAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAQgGACABAHIAAAGIAYAAQAAAAAAABQABAAAAAAQAAAAAAABQABAAAAABIAAAHQAAABgBAAQAAABAAAAQAAABgBAAQAAAAAAAAIgYAAIAAAVQgBAPgYAAgAAIAGIgKgGQABAAAFgHIACgBIAPAIIALAHIgBABIgHAJgAgPgdIgGgKQAAgBAAAAQAAgBABAAQAAAAABAAQABgBAAAAQAOgBAMgDIgQgPQAAAAgBABQgBAAAAAAQgBAAAAAAQgBAAgBAAQAAAAAAAAQgBAAAAAAQgBAAAAAAQAAgBAAAAIgHgHIgCgDIABAAIAUgGQAMgFAJgGQAGgDAGgFIAKgKIACgBIAQAHIABACQAAABAAABQAAAAAAABQgBAAgBAAQAAAAgBAAIgHACIgDADIAzAAIAFAAQAAABABAAQAAABAAAAQAAABAAAAQAAABAAAAQgLAPgPALQgRAMgXAJQgXAJgaADQAAAAAAAAQgBAAAAAAQgBgBAAAAQgBgBAAAAgAAEhBIAUAOQAMgDAGgDIgZgPgAAchOQASAIAKAGIAFgEQAJgEAIgIIgwAAg");
	this.shape.setTransform(402.7,10.85);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("ABTBiQgdgRgQgUQgPgRgHgRQgGgKgHgYIgDAMQgGATgLARQgKAQgNANQgPAOgkAUQgBAAAAAAQgBgBAAAAQgBAAAAgBQgBAAAAgBIgKgJQAAgBgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBIAUgJQAPgIAJgHQALgIAJgLQAKgNAIgPQAHgPAEgPIADgLIheAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAgKQAAgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAIBhAAIABgJQACgWgCggIAZADQAAAAAAABQAAAAgBABQAAAAAAAAQgBABAAAAQgEACAAADQAAAbgDAZIBhAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAAAKQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAIhcAAQAEAQAHAMQAEAOAKAOQANATATAOQAPANAVAHIACACQAAAAAAABQAAAAgBABQAAAAgBABQAAAAgBABIgJAKQgCADgDAAg");
	this.shape_1.setTransform(374.65,11.025);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAwBoQgEAAAAgDIAAh8IgtAAQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIAAgIQAAgBAAAAQAAgBAAAAQABgBAAAAQABAAABAAIAtAAIAAhAQAAAAAAgBQAAAAABgBQAAAAABAAQABAAABAAQASAAAAACQAAABAAABQgBAAAAABQAAAAgBABQAAAAgBAAQgCAAAAAFIAAA3IAwAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAAAIQAAABAAAAQAAABAAAAQgBABAAAAQgBAAgBAAIgwAAIAAB8QAAADgEAAgAgeBoQgEAAAAgDIAAgKIgyAAIAAAKQAAADgEAAIgJAAQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAgBAAgBIAAhEQAAgBAAAAQABgBAAAAQABgBAAAAQABAAABAAIBNAAQABAAAAAAQABAAAAAAQABABAAAAQAAABAAABIAABEQAAABAAABQAAAAgBABQAAAAgBAAQAAAAgBAAgAhUBMIAyAAIAAggIgyAAgAhfAKQgBAAgBAAQAAgBAAAAQgBgBAAAAQAAgBAAgBIAAgGQAAgBAAgBQAAAAABgBQAAAAAAAAQABgBABAAIBKAAQAAAAABABQAAAAABAAQAAABAAAAQAAABAAABIAAAGQAAABAAABQAAAAAAABQgBAAAAABQgBAAAAAAgAhegVQgBAAgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBIAAgIQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAABAAIBJAAQAAAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAAAIQAAABAAAAQAAABAAAAQgBABAAAAQgBAAAAAAgAhtg1QAAAAgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIAAgHQAAgBAAgBQAAAAAAgBQABAAAAgBQABAAAAAAIBmAAQABAAAAAAQABABAAAAQAAABABAAQAAABAAABIAAAHQAAABAAAAQgBABAAAAQAAABgBAAQAAAAgBAAgAhdhUQgBAAgBAAQAAgBAAAAQgBgBAAAAQAAgBAAgBIAAgHQAAgBAAgBQAAAAABgBQAAAAAAgBQABAAABAAIBGAAQABAAAAAAQABABAAAAQAAABABAAQAAABAAABIAAAHQAAABAAABQgBAAAAABQAAAAgBABQAAAAgBAAg");
	this.shape_2.setTransform(346.525,11.075);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhoBnQgBAAgBAAQAAAAgBgBQAAAAgBgBQAAAAAAgBIAAhDQAAgBAAgBQABAAAAgBQABAAAAAAQABgBABAAIBIAAQABAAAAABQABAAABAAQAAAAABABQAAAAAAABIAABEQAAAAAAABQgBAAAAAAQgBABgBAAQAAAAgBAAIgKAAQgBAAAAAAQgBAAgBgBQAAAAgBAAQAAgBAAAAIAAgJIgtAAIAAAJQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAgAhbBMIAtAAIAAggIgtAAgABLBeQgOgGgLgHIgHgEQgJAGgSAJQgKAFgQAEQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAgBgBAAIgHgJIACgCIAUgGQATgHALgJIgBgBQgKgIgEgMQgHgJgGgTIAAgCQAAgBAQgCQACALAFAKQAEAIAJAMIAEADIAKgLQAIgLAFgMQAEgIADgJIhRAAQgBAAAAAAQgBAAAAgBQAAAAgBgBQAAgBAAgBIAAgGQAAgBAAgBQABAAAAgBQAAAAABAAQAAAAABAAIBcAAQAAAAABAAQAAAAABAAQAAAAABAAQAAABABAAIAFAHQgJAYgEAJQgIAPgHAJIgJAJQAKAHANAGQAPAGARADIADACIgCACQgEACgEAGIgDACgAhlAKQgBAAgBAAQAAAAgBAAQAAgBAAAAQAAgBAAgBIAAgHQAAAAAAgBQAAgBAAAAQABgBAAAAQABAAABAAIBCAAQABAAAAAAQABAAAAABQAAAAABABQAAABAAAAIAAAHQAAABAAABQgBAAAAABQAAAAgBAAQAAAAgBAAgAgNgWIgGgHIgCgDQASgJAFgOQADgKAAgNIAAgVQAAgBAAAAQABgBAAAAQAAgBABAAQAAAAABAAIA6AAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAAA1QAAABAAAAQAAABABAAQAAABAAAAQABAAAAAAQADACAEAAIAJAAQAFAAACgEQABgDADgOQAAgBAAAAQAAAAAAgBQABAAAAAAQABAAAAAAIALAEQABAAABABQAAAAABAAQAAABABAAQAAABAAABQgEAQgEAJQgDAGgLAAIgYAAQgKAAgEgCQgDgDAAgEIAAg3IgeAAIAAALQAAANgEAOQgDALgJAIQgFAGgJAGQgBAAgBAAQAAAAgBgBQAAAAgBAAQAAAAgBgBgAhkgWQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAAAIAAgIQAAgBAAgBQAAAAAAgBQABAAAAAAQABAAABAAIBBAAQABAAAAAAQABAAAAAAQAAABABAAQAAABAAABIAAAIQAAAAAAABQgBABAAAAQAAABgBAAQAAAAgBAAgAhvg2QAAAAgBAAQgBAAAAgBQAAAAgBgBQAAgBAAgBIAAgGQAAgBAAgBQABgBAAAAQAAgBABAAQABAAAAAAIBWAAQABAAAAAAQABAAAAABQAAAAABABQAAABAAABIAAAGQAAABAAABQgBABAAAAQAAABgBAAQAAAAgBAAgAhjhWQgBAAgBAAQAAAAgBAAQAAgBAAAAQAAgBAAgBIAAgIQAAAAAAgBQAAgBAAAAQABgBAAAAQABAAABAAIBAAAQABAAAAAAQABAAAAABQAAAAABABQAAABAAAAIAAAIQAAABAAABQgBAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_3.setTransform(318.825,11.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AANBqIgLgHIgCgCQAAAAAAAAQAAgBABAAQAAAAAAAAQAAAAABAAQATgIAKgGQAMgHAGgHIgFgGQgLgOgHgTIgCgFIgDALQgFAVgPAXQgJAPgNAKIgCAAQgEgEgFgCIgBgEQAPgMAKgSQAKgVAFgWQAFgWAAgiIAAg0IgUAAQgBAAAAAAQgBAAAAgBQAAAAgBgBQAAAAAAgBIAAgIQAAAAAAgBQABAAAAgBQAAAAABAAQAAAAABAAIBaAAIAFAAQAFAEAAACIgWBCIAcAAQADAAACACQAFADAAABIgHAhQgDAMgIARQgFALgGAJIgHAJIACACQAOAMAaANIgCADQgFACgEAEQAAAAgBAAQAAABgBAAQAAAAgBAAQAAAAgBAAQgQgJgMgJIgKgIQgGAHgMAIQgJAGgRAIQgBAAAAAAQgBgBgBAAQAAAAAAgBQgBAAAAgBgAAlASQAGAPAIAOIAJALIAKgOQAHgMAFgOQAFgSADgNIg7AAQACATAEAMgAAdgcIAYAAIAVg7IgtAAgAhBBrQgEAAAAgDIAAhbIgcAHQgHAHgBAAQgCAAgDgWQAAgCAQgDIAYgaIgVgPQgNgIgJgDQAAgCAKgKQAAgBABAAQAAAAAAAAQABgBAAAAQAAAAABAAIAHAFQAKgLAGgJIARgbIATAKIABADQAAABAAAAQAAAAgBAAQAAABgBAAQgBAAgBAAQgGAAgBADIgeAnIASAQIAHgJQAQgTALgRIARAQQAAAAAAABQAAAAgBAAQAAABgBAAQAAAAgBAAQgIAAAAACQgfAngRASIArgFIgHgRQAAgCAMgFIAMAbIAHAYQAAABgQAEIgEgVIAAgBIgbAHIAABfQAAADgEAAgAhvBcQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAQAHgKAEgMQAEgLADgXQAAAAAAgBQABAAAAgBQAAAAABAAQABAAAAAAQATAEAAABQAAABAAABQgBAAAAABQAAAAgBAAQAAABgBAAQgDACgBACQgDAUgFAOIgGAPIgCABgAgfBIIgIgnQAAgCAMgCIABACQAEAMAGAbQAAACgNACQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAgBAAAAg");
	this.shape_4.setTransform(290.625,10.875);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAgBoQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAgBAAgBIAAhNQAAAAAAgBQABAAAAgBQABAAAAAAQABAAABAAQATAAAAACQAAABAAABQAAAAgBABQAAAAAAABQgBAAAAAAQgDABAAAEIAABEQAAADgEAAgAg/BmIgJgGQgBAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAgBIABgBQANgIAGgKQAGgJADgNQACgIAAgWQAAAAAAAAQAAgBABAAQAAAAAAAAQABAAAAAAIATABQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABQAAADgEABQAAAAgBAAQAAAAAAAAQgBAAAAABQAAAAAAABQgBAVgCALQgEANgGAJQgHAJgLAHgAhjAvIgJgJQAAgBgBAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIABgBQAKgCAMgGQANgGAMgJQAIgEAGgHIALgLIACgCIATAJQABABABAAQAAAAAAABQABAAAAAAQAAABAAAAQAAACgFAAQgGAAgCACQgGAIgMAJIgkAWIgQAHQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAgBAAAAgABIAkQgOgHgMgKQgJgIgPgQIANgKIhiAAIAAAFQAAABAAAAQAAABgBAAQgBAAAAABQgBAAgBAAIgJAAQgBAAgBAAQgBgBgBAAQAAAAAAgBQgBAAAAgBIAAhaQAAgDAFAAICbAAQABAAABAAQABAAAAAAQABABAAAAQAAABAAAAIAABcQAAABAAAAQAAABgBAAQAAAAgBABQgBAAgBAAIgJAAQgBAAgBAAQgBgBgBAAQAAAAAAgBQgBAAAAgBIAAgGIgdAAQAIALAKAIQALAKAJAFQAQAJATAFIADABIgCADIgKAIIgCACQgRgEgJgHgAAIgdIA5AAIAAgXIg5AAgAg/gdIA2AAIAAgXIg2AAgAAIhCIA5AAIAAgXIg5AAgAg/hCIA2AAIAAgXIg2AAg");
	this.shape_5.setTransform(262.45,11.075);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AhPBpQgBAAgBAAQAAgBgBAAQAAAAAAgBQgBAAAAgBIAAiFIgaAAQAAAAgBAAQgBgBAAAAQAAgBgBAAQAAgBAAgBIAAgJQAAAAAAgBQABAAAAgBQAAAAABAAQABAAAAAAIAaAAIAAgxQAAgBABgBQAAAAAAgBQABAAAAAAQABAAABAAQATAAAAADQAAAAAAABQAAABAAAAQgBAAAAABQgBAAAAAAQgCAAAAAFIAAApIAuAAIAAg3QAAgDAEAAQATAAAAADQAAABAAAAQgBABAAAAQAAABgBAAQAAAAgBABQgCAAAAAEIAAAvIA1AAIAAg2QAAgBAAAAQABgBAAAAQABAAABgBQAAAAABAAQAUAAAAADQAAABAAAAQgBABAAAAQAAABgBAAQAAAAgBAAQgCABAAAEIAAAuIAmAAQABAAAAAAQABAAAAAAQAAABABAAQAAABAAAAIAAAJQAAABAAABQgBAAAAABQAAAAgBABQAAAAgBAAIgmAAIAABUQAAADgFAAIgKAAQgBAAAAAAQgBgBgBAAQAAAAgBgBQAAAAAAgBIAAgQIg1AAIAAAQQAAADgEAAIgKAAQgBAAAAAAQgBgBgBAAQAAAAgBgBQAAAAAAgBIAAhUIguAAIAABuICqAAQABAAABAAQAAABAAAAQABAAAAABQAAABAAAAIAAAJQAAABAAABQAAAAgBABQAAAAAAABQgBAAgBAAIiqAAIAAAHQAAADgFAAgAAAAVIA1AAIAAg0Ig1AAg");
	this.shape_6.setTransform(234.575,10.925);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AA8BIIAIgJIguAAIAHAEIACADQAAABAAAAQAAAAAAAAQgBAAAAAAQgBABAAAAIgFABIgRAOIgaAPQgBAAgBgBQAAAAgBAAQAAAAgBgBQAAAAAAAAIgJgHIgBgBIABgBIANgGQAMgGAHgGIALgKIgVAAQgEgBAAgDIAAh0QAAAAAAgBQAAAAABAAQAAgBABAAQABAAABAAIAgAAIAHgPIAFgMIgyAAQgBAAAAAAQgBAAAAgBQAAAAgBgBQAAgBAAAAIAAgIQAAgBAAgBQABAAAAgBQAAAAABAAQAAgBABAAIB8AAQABAAAAABQABAAAAAAQAAABABAAQAAABAAABIAAAIQAAAAAAABQgBABAAAAQAAABgBAAQAAAAgBAAIg4AAIgLAbIA5AAQABAAABAAQABAAAAABQABAAAAAAQAAABAAAAIAAB0QAAADgEABIgXAAQATAPAUAKIgCADQgHALgBAAQgWgMgWgSgAACAwIBTAAIAAgVIhTAAgAACAMIBTAAIAAgUIhTAAgAACgXIBTAAIAAgVIhTAAgAhxAvQAUgEAUgHIAAhnIgfAAQgBAAgBAAQAAAAAAgBQgBAAAAgBQAAgBAAAAIAAgIQAAgBAAgBQAAAAABgBQAAAAAAAAQABgBABAAIBMAAQAAAAABABQAAAAABAAQAAABAAAAQAAABAAABIAAAIQAAAAAAABQAAABAAAAQgBABAAAAQgBAAAAAAIgbAAIAABhIAbgKIABgBQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABQAAAMgBAAQgoARggAJQgDAHgCAAQgDAAgHgTg");
	this.shape_7.setTransform(206.425,11.35);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AhdBlQgBAAgBgBQAAAAgBAAQAAgBgBAAQAAgBAAAAIAAiTQAAgEAEABIBUAAIAAgiIhhAAQAAAAgBAAQAAAAgBAAQAAgBAAAAQAAgBAAgBIAAgHQAAgBAAgBQAAAAAAgBQABAAAAAAQABAAAAAAIDVAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAABIAAAHQAAABAAABQAAAAAAABQgBAAAAAAQgBAAAAAAIhjAAIAAAiIBVAAQAEgBABAEIAACDQgBAIgJAEQgJAEgRACQgBAAAAgBQAAAAgBAAQAAAAAAgBQgBAAAAgBQgBgHgEgHQAAgBAAAAQAAAAAAgBQAAAAABAAQAAAAAAAAQASAAADgBQAFgDAAgDIAAgbIgBABQgJAHgCAAQgNgQgFgPIgDgGIgDAHIgJARQgFAIgHAHQgBAAAAAAQgBAAAAAAQgBgBAAAAQgBAAAAAAIgJgJIgBgCIAJgJIALgRIAIgTIgQAAQgBAAAAAAQgBAAAAAAQgBAAAAgBQAAgBAAgBIAAgHQAAgBAAgBQAAAAABgBQAAAAABAAQAAgBABAAIAkAAQABAAAAABQABAAAAAAQAAAAAAABQABAAAAABQgBARAHAOQAFAOAJAKIAAhSIhJAAIAACGQAAABgBAAQAAABAAAAQgBAAgBAAQgBABgBAAIgIAAQgBAAgBgBQgBAAAAAAQgBAAAAgBQAAAAAAgBIAAgvQgIAHgCAAQgMgOgHgRIgCgFIgCAGIgKAQIgLAPQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAAAgBAAIgIgJIgBgCIAJgJIAKgQIAJgTIgUAAQAAAAgBgBQAAAAAAAAQgBAAAAAAQAAgBAAgBIAAgHQAAgBAAgBQAAAAABgBQAAAAAAAAQABgBAAAAIAmAAQABAAAAABQAAAAAAAAQABAAAAABQAAAAAAABQAAARAHAOQAGANAHAKIAAhSIhHAAIAACIQAAAAAAABQAAAAgBABQAAAAgBAAQgBABAAAAg");
	this.shape_8.setTransform(178.55,11.45);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgxBMIAAiXIBjAAIAAAPIhSAAIAAA0IBIAAIAAAOIhIAAIAABGg");
	this.shape_9.setTransform(156.825,11.625);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgIBMIAAhlIARAAIAABlgAgIg5IAAgSIARAAIAAASg");
	this.shape_10.setTransform(142.825,11.625);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgEAFQgRgPgJgHIAMgMQAZAUAYAcIgOALg");
	this.shape_11.setTransform(122.975,10.9);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AhlBpIgIgDQgBAAAAAAQgBgBAAAAQAAAAAAAAQAAgBAAAAQAJgUACgRQABgBAAAAQAAgBAAAAQABgBAAAAQABAAAAAAIAJABQABAAAAABQABAAAAAAQAAAAABABQAAAAAAAAQgEAagFAQIgBABIgGgBgABdBpQgBAAAAgBQgBAAAAAAQAAgBgBAAQAAgBAAAAIAAgQIg5AAIAAAQQAAAAAAABQAAAAgBABQAAAAgBAAQAAABgBAAIgKAAQgBAAAAgBQgBAAAAAAQAAgBgBAAQAAgBAAAAIAAhjQAAgBAAAAQABgBAAAAQAAAAABAAQAAgBABAAIAbAAIAAhnQAAgBAAAAQAAgBABAAQAAAAABAAQABgBABAAQASAAAAADQAAABAAAAQAAABAAAAQgBABAAAAQgBAAAAAAQgDABAAAEIAAAnIAuAAQABAAAAAAQAAAAABABQAAAAAAAAQAAABAAAAIAAAIQAAABAAABQAAAAAAABQgBAAAAAAQAAAAgBAAIguAAIAAArIAnAAQABAAAAABQABAAAAAAQABAAAAABQAAAAAAABIAABjQAAAAAAABQAAAAgBABQAAAAgBAAQAAABgBAAgAAhBIIA5AAIAAg6Ig5AAgAhGBoQgBAAgBgBQgBAAgBAAQAAAAAAgBQgBAAAAAAQACgZAAgRQAAAAAAgBQABAAAAAAQAAAAAAAAQABAAAAAAIAIAAQAAAAABAAQABAAAAAAQAAAAABAAQAAABAAAAQABAUAAAWQAAAAAAAAQAAABAAAAQgBAAAAAAQgBABAAAAgAgnBiQgCgRgFgWQAAgBAAAAQAAgBAAAAQABAAAAAAQABAAAAAAIAHAAQABAAAAAAQABAAAAAAQABAAAAABQABAAAAABQAJAWACARQAAAAAAABQgBAAAAAAQAAABgBAAQAAAAgBAAIgMABQAAAAgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBgAgHBeQgEgTgGgVQAAAAAAAAQAAgBAAAAQABAAAAAAQABgBAAAAIAJgCIACACQAHARAHAWQAAAEgEAAIgLACQAAAAgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBgAhoAzIgFgOQAAAAAAAAQAAgBAAAAQABAAAAAAQABAAABgBIAmgBIAIgBIAAgZIgpAAQAAAAgBAAQAAAAAAgBQAAAAgBgBQAAAAAAgBIAAgHQAAAAAAgBQABAAAAgBQAAAAAAAAQABAAAAAAIApAAIAAgVIgrAAQgBAAAAAAQgBAAgBgBQAAAAgBAAQAAgBAAgBIAAhGQAAgDAEABIBoAAQABAAABAAQAAAAABAAQAAABAAAAQABABAAAAIAABGQAAABgBABQAAAAAAAAQgBABAAAAQgBAAgBAAIgsAAIAAAVIArAAQABAAAAAAQAAAAAAAAQABABAAAAQAAABAAAAIAAAHQAAABAAAAQAAABgBAAQAAABAAAAQAAAAgBAAIgrAAIAAAXQAZgDAWgEQAAAAABABQAAAAAAAAQAAABABAAQAAABAAAAIgCAJQAAAFgDAAQggAEg8AFQgFAAgCABIgDABQAAAAgBAAQgBAAAAAAQgBAAAAgBQAAAAAAAAgAgrgmIAhAAIAAgwIghAAgAhagmIAeAAIAAgwIgeAAgAgfgvIgIgDIgBgCIAAgBQAGgHABgFQAFgIABgGIABgCIAMAFQABAAAAABQABAAAAAAQAAABABAAQAAABAAAAQAAAAAAABQgBAAAAAAQAAAAAAAAQgBAAAAAAQgBAAAAABQAAAAgBAAQAAAAAAABQAAAAAAAAIgLAXIgCABgAhRg5QgBgEgGgMQAAgBAKgFIAJAQIAFAOIgNADIgEgLg");
	this.shape_12.setTransform(94.975,11.05);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AhBBqQgBAAAAAAQgBAAAAgBQAAAAgBgBQAAAAAAgBIAAhcIggAJQgFAFgBAAQgBAAgEgUQAAgBARgEIAbgdIgVgQQgPgIgIgDQAAgCAKgKIACgCIAJAFIAOgRIAPgXIATAKIABACQAAABAAAAQAAABgBAAQAAAAgBAAQgBAAgBAAQgGAAgBADIgaAhIATAQIACgCQARgUAKgPQAQAMAAACQAAAAAAAAQgBAAAAABQAAAAgBAAQgBAAAAAAQgHAAgCACQgVAbgZAdIAtgHIgHgOQAAgBAMgHIAVAzIgPAEQgBgHgFgNIgBgDIgcAGIAABhQAAABgBAAQAAABAAAAQgBABAAAAQgBAAgBAAgAhtBbQAAAAgBgBQAAAAgBAAQAAAAAAgBQAAAAAAAAQAEgIAGgOQAEgOACgUQAAAAAAgBQABAAAAAAQAAgBABAAQAAAAABAAQATADAAACQAAACgDACQgEACAAACQgDAXgEAKIgGAQQAAAAAAAAQAAAAgBABQAAAAAAAAQAAAAgBAAgAgHBdQgBAAgBgBQAAAAAAAAQgBgBAAAAQAAgBAAgBIAAgHQAAgBAAgBQAAgBABAAQAAgBAAAAQABAAABAAIAvAAIAAiVIgqAAQgBAAgBgBQAAAAgBAAQAAgBAAAAQAAgBAAgBIAAgIQAAAAAAgBQAAgBAAAAQABgBAAAAQABAAABAAIBpAAQAAAAABAAQABAAAAABQAAAAABABQAAABAAAAIAAAIQAAABAAABQgBAAAAABQAAAAgBAAQgBABAAAAIguAAIAACVIA1AAQAAAAABAAQAAAAABABQAAAAAAABQAAABAAABIAAAHQAAABAAABQAAAAAAABQgBAAAAAAQgBABAAAAgAgdBKQgDgSgHgYQAAgCAMgCQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAABQAHANAIAdQAAACgPACQAAAAgBAAQgBAAAAAAQAAgBgBAAQAAgBAAAAg");
	this.shape_13.setTransform(67.025,10.9);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("ABLBmQgOgDgNgEIgDgCQgNAFgVAEIggAEQAAAAgBAAQgBAAAAAAQgBgBAAAAQgBAAAAgBIgFgHIgBgCQAAAAAAAAQAAAAAAAAQAAAAABAAQAAAAAAAAIAZgDQAQgDAPgEQgKgFgFgGQgGgFgFgJIgSAAQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAgBAAAAIAAgIQAAgBAAAAQAAgBABAAQAAAAAAAAQAAAAABAAIBvAAIADABIAFAFQgIAMgHAFQgJAHgJAGIgDABIALACQAPAEAUACIADABIgCACIgIAIIgDACgAAUBAQAFAGAJAFIALAEQAIgDAEgCQAIgEAIgIIADgCIg8AAgAhaBnIgEgOIgCgDIASACQAMAAADgGQACgFACgMQACgVAAgOIgBgRIgEAFIgPAUQgJAJgKAHQAAAAgBAAQgBAAAAAAQgBAAAAAAQAAgBgBAAIgIgIIgBgDQAHgEAHgGQAJgHAIgMIAQgZQgDgQgEgHIgCgGIgdAbQgBAAgBgBQAAAAgBAAQAAAAgBgBQAAAAgBgBIgGgFQgBAAAAAAQAAgBAAAAQgBAAAAgBQAAAAAAAAIAXgUIAMgNIgGgJQgIgLgKgJQAAgCAKgLQARAQAIAMIACgDQAKgQAFgNQAAgBAAAAQAAAAAAgBQAAAAAAAAQAAAAABAAQARAJAAABQAAAAAAABQAAAAgBAAQAAABAAAAQAAAAgBAAQgDABgBABQgKAUgLAPIAGAPQAFAOAEATQAEAZAAANQAAAfgEAQQgDAOgFAGQgDAFgHABQgOADgMAAQgBAAAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBgAgMAmQgBAAgBgBQAAAAAAAAQgBgBAAAAQAAgBAAgBIAAg6IgHAHIgFADIgDgBIgJgFIgCgBIACgBIATgTQAIgKAFgMQABgBAAAAQAAgBABAAQAAgBABAAQAAAAAAAAIAMAFQABAAABABQAAAAABABQAAAAABABQAAAAAAABQAAAAAAAAQgBABAAAAQgBAAAAAAQgBABgBAAQgEAAgCADIAAACIAjAAIAMgRIAPAIQAAAAABAAQAAABABAAQAAABAAAAQAAABAAAAIgCAAIgHAGIAxAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAABIAAAIQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAAAAAIgwAAIAAAMIArAAQABAAAAAAQABAAAAABQAAAAAAAAQAAABAAABIAAAHQAAABAAAAQAAABAAAAQAAAAgBAAQAAABgBAAIgrAAIAAALIArAAQABAAAAABQABAAAAAAQAAAAAAABQAAAAAAAAIAAAHQAAABAAABQAAAAAAAAQAAABgBAAQAAAAgBAAIgrAAIAAAMIA0AAQAAAAABAAQAAAAAAABQAAAAABAAQAAABAAAAIAAAIQAAABAAAAQgBABAAAAQAAAAAAAAQgBAAAAAAIhuAAQAAADgDABgAAAAWIAqAAIAAgMIgqAAgAAAgCIAqAAIAAgLIgqAAgAAAgaIAqAAIAAgMIgqAAgAA3hEQgBAAAAgBQgBAAAAAAQAAgBgBAAQAAgBAAgBIAAgfQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAABAAQARAAAAADQAAAAAAABQAAAAAAABQgBAAAAAAQAAAAgBAAQAAABgBAAQAAAAAAABQAAAAgBABQAAABAAABIAAACIAmAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAAAIAAAHQAAABAAABQAAABgBAAQAAABAAAAQgBAAAAAAIgmAAIAAAIQAAABAAABQAAAAgBABQAAAAgBAAQAAABgBAAgAAMhEQgBAAgBgBQAAAAAAAAQgBgBAAAAQAAgBAAgBIAAgIIgkAAQAAAAAAAAQgBAAAAgBQAAAAAAgBQAAgBAAgBIAAgHQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAAAAAIAkAAIAAgKQAAgBAAAAQAAAAABgBQAAAAAAAAQABAAABAAQARAAAAADQAAAAAAABQAAAAAAABQgBAAAAAAQAAAAgBAAQAAABgBAAQAAAAAAABQgBAAAAABQAAABAAABIAAAXQAAABAAABQAAAAgBABQAAAAgBAAQAAABgBAAg");
	this.shape_14.setTransform(38.825,11.15);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgDBpQgEAAAAgDIAAgxIgGAFQgNALgNAGQgNAJgSAGIgZAIQAAAAgBAAQAAAAgBAAQAAgBAAAAQgBgBAAgBIgHgHIgCgDQAUgFAUgHQAQgGASgKQAGgEANgMIg4AAQgBAAAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIAAgIQAAAAAAgBQAAAAAAgBQABAAAAAAQAAAAABAAIA/AAIAAgUQAAgDAEAAQARAAAAADQAAAAAAABQAAABAAAAQAAAAgBABQAAAAgBAAQgCABAAAEIAAAMIBCAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAABAAAAIAAAIQAAABAAAAQAAABAAAAQAAABgBAAQAAAAAAAAIg7AAQAMAKAMAIQAOAIAUAIQAUAHAOADQAAAAgBABQAAAAAAAAQAAABgBAAQAAAAgBABIgKAJIgCACQgZgIgQgIQgUgLgLgJIgMgLIAAAyQAAADgFAAgABbAiQgBAAgBAAQAAgBgBAAQAAAAgBgBQAAAAAAgBIAAgeIirAAIAAAdQAAABAAABQAAAAgBAAQAAABgBAAQAAAAgBAAIgKAAQgBAAgBAAQAAAAgBgBQAAAAAAAAQgBgBAAgBIAAgnQAAgBABgBQAAAAAAAAQABgBAAAAQABAAABAAIAPAAIAAgBIgHgGQgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAAAQAPgHAGgFQAGgEAFgHQAFgIACgJQACgIAAgJIAAgXQAAgBAAAAQAAgBAAAAQAAAAABgBQAAAAAAAAIAUADQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAQgDACABAEIAAAOIgCATIgCAFQAHAKAFADQAHAJAKAFQAAABAAABQAAAAAAABQgBAAAAAAQAAABgBAAIgJAHIgBAAQgGgFgFgFIgMgOIAAAAQgHAJgIAHQgIAGgMAGICzAAQABAAABAAQAAAAABABQAAAAAAAAQAAABAAABIAAAoQAAABAAAAQAAABAAAAQgBAAAAABQgBAAgBAAgABUgOQgGgDgJgHIgPgQIAAAAQgEAHgJAIQgFAEgOAHQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIgIgGQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAgBIASgKQAGgFADgGQAEgGADgIIABgQIAAgZQAAgBAAAAQAAgBAAAAQAAAAABgBQAAAAAAAAQAUACAAABQAAAAAAABQAAAAgBABQAAAAAAAAQgBABAAAAQgCACAAAEIAAAQIgDARIAAADQAJALAGAEQAJAIANAGQAAABAAAAQAAABAAAAQgBABAAAAQAAABgBAAIgKAIgAhfgyQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAgBAAAAQAFgHADgGQACgGADgPQAAAAAAAAQAAgBABAAQAAAAAAAAQABAAAAAAQASADgBACQAAAAAAABQAAAAAAABQAAAAgBAAQAAABgBAAQAAAAgBAAQAAABAAAAQgBAAAAABQAAAAAAAAQgDANgDAIIgFAIIgCABgAAEgzQAAAAAAAAQgBgBAAAAQAAAAAAAAQAAgBAAAAQADgFAFgHQADgHACgMQAAAAAAgBQAAAAABAAQAAAAAAAAQAAAAABAAQAPACAAACQAAAAAAABQAAAAAAAAQAAABgBAAQAAAAgBABQAAAAgBAAQAAABAAAAQgBAAAAABQAAAAAAAAQgDALgDAHIgEAIIgCACgABGg4IAAgBIAJgNIAHgPIABgCIAOAFIACADIgBACQgBAAAAAAQgBAAAAAAQAAABgBAAQAAAAAAABQgFAOgIAKIgBACgAgYg3IgCgBIABgBIAFgNIAFgPIABgCIAMAEQABAAAAABQABAAAAAAQAAABAAAAQAAAAAAABQAAAAAAAAQAAABAAAAQAAAAAAAAQAAABgBAAQAAAAAAAAQAAAAgBAAQAAABAAAAQAAABgBAAQgFASgDAGQAAAAAAABQAAAAgBAAQAAABAAAAQAAAAgBAAg");
	this.shape_15.setTransform(10.85,11.025);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,413.9,21.8);


(lib.sb_bg2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.518)","rgba(255,255,255,0)"],[0,0.494,1],-1220,-0.1,1219.9,-0.1).s().p("Ei+nAs/MAAAhZ9MF9PAAAMAAABZ9g");
	this.shape.setTransform(-55.761,152.2271,0.4844,4.7721,44.4007);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#000000","rgba(67,67,67,0)"],[0.325,1],-1220,-0.1,1219.9,-0.1).s().p("Ei+nAs/MAAAhZ9MF9PAAAMAAABZ9g");
	this.shape_1.setTransform(2400.8083,249.9905,0.6514,2.3538,-168.3118);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#000000","rgba(68,68,68,0)"],[0.145,1],-1220,-0.1,1219.9,-0.1).s().p("Ei+nAs/MAAAhZ9MF9PAAAMAAABZ9g");
	this.shape_2.setTransform(-1472.9277,151.87,0.7871,2.3538,11.6882);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// bg2
	this.instance = new lib.bg2();
	this.instance.setTransform(-1871,-24,2.7702,2.7702);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-2550.5,-1242.7,5866.8,2789.9);


(lib.mo_ccc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_25
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["rgba(255,255,255,0)","#FFFFFF","rgba(255,255,255,0)"],[0.365,0.494,0.6],0,0,0,0,0,93).s().p("AqLKMQkOkOAAl+QAAl9EOkOQEOkOF9AAQF+AAEOEOQEOEOAAF9QAAF+kOEOQkOEOl+AAQl9AAkOkOg");
	this.shape.setTransform(92.2,92.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(50));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,184.4,184.4);


(lib.sb_start = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_5
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AATBmQgXgBABgYIAAhmIgGAGIgGgHIAAAMIgYAAIAAAWIAXAAIAAAYIgXAAIAAAiIAagFIAEAXQgtAMgsAIIgKgbIAJgBIAAhHIAaAAIAABDIAIgCIAAhUIggAAIAAhTIBSAAIAAAqIAIgOQAKgTAEgQIAaAIIgFAOIBOAAQAABzgJANQgGAOgQAAIgVgBIgFgbQAMACAKAAQAEAAACgIQACgKABhJIg/AAIgJAOIA8AAIAABKIguAAIAAAmQAAAHAIACQAGACAOAAIASgBQAEAAAEgCQAEgDACgNIAbALQgCAMgFALQgFAHgKABQgLACgaAAQgZAAgGgDgAAWAGIAUAAIAAgXIgUAAgAhHgnIAeAAIAAghIgeAAg");
	this.shape.setTransform(325.85,10.675);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhiBqIAAjTIBbAAIAABXIhDAAIAAB8gAhKgqIAsAAIAAgIIgsAAgAhKhIIAsAAIAAgJIgsAAgAAxBnIgGgcQANAEAJAAQAIAAAAgSIAAhPIhCAAIAAhXIBbAAIAACwQAAAigdAAQgKAAgKgCgAAggqIApAAIAAgIIgpAAgAAghIIApAAIAAgJIgpAAgAhABQQANgIAIgNIADgGIgXAAIAAgYIAaAAIAAgQIgUAAIAAgXIBzAAIAAAXIgXAAIAAAQIAbAAIAAAYIgbAAIAAAtIgaAAIAAgtIgWAAQgDANgFAJQgKAQgRAJgAgLAdIAUAAIAAgQIgUAAg");
	this.shape_1.setTransform(284.25,10.975);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABEBrIAAgHIh3AAIAAAHIgaAAIAAhGICrAAIAABGgAgzBNIB3AAIAAgQIh3AAgAhNAgIAAg6IgIAHIgTgTQAPgNALgQQAMgRAIgWIAZAFIgFANIAsAAIAFgSIAcAGIgGAMIBGAAIAAAXIhHAAIAAAJIA+AAIAAAWIg+AAIAAAIIA+AAIAAAXIg+AAIAAAHIBJAAIAAAXIicAAIAAAFgAgzAEIA3AAIAAgHIg3AAgAgzgaIA3AAIAAgIIg3AAgAgzg8IAAAEIA3AAIAAgJIg1AAg");
	this.shape_2.setTransform(242.8,10.925);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("ABKBfIgVgPIAOgLIgoAAIANALQgUAPgbAKIgOgZQASgEAMgHIgNAAIAAiJIAhAAIACgLIgoAAIAAgZIBwAAIAAAZIgtAAIgCALIArAAIAACJIgSAAIAJAFQALAFAHABIgOAZIgUgKgAAVAsIAzAAIAAgOIgzAAgAAVAHIAzAAIAAgOIgzAAgAAVgeIAzAAIAAgNIgzAAgAhkBlIgFgbQAOAEALgBQAAAAABAAQAAAAABAAQAAgBAAAAQABgBAAAAIABgMIAAhEIgfAAIAAgYIApAAQgPgNgSgLIASgTIARALQALgKAHgIIg6AAIAAgZIBbAAIAAAXQgMATgRARIAHAGIgIAKIAjAAIAAATQgIATgMASIgSgNIAJgTIgMAAIAABKQAAASgFAIQgHAJgQgBQgMAAgLgCg");
	this.shape_3.setTransform(201.925,11.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AA0AxQgLgcgFgnIgNACIAABWIAZgHIAFAYQgaAKgiAIIgJgaIAOgDIAAhpIgGAIIgVgRIAHgJIgjAAIAAAUIAoAAQAABlgLATQgGAMgOAAQgKAAgJgCIgGgaQgGAQgHAOIgXgSQANgZAGgeQAFgcAAghIAAgUIgUAAIAAgaIAfAAIAAghIAbAAIAAAhIAdAAIAAATIAIgRQAJgSAEgRIAaAHIgFAQIBMAAIAAAZIhXAAIAAABIgMAWIAkgHQATgFASgHIAWAWIgkAKQACATAEANQAMgJAJgIIASASQgQAOgQAIIABACQAKAaAaAZIgRAVQgegcgLgegAhCA1IgHAXQAHABANAAQAFAAABgGQACgQACg3IgPAAQgDAcgFAZg");
	this.shape_4.setTransform(134.825,10.925);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AARBrIAAhgIgKATQgbAmgQANIgOgYQATgRATgeQANgXAJgXIgyAAIAAgbIA5AAIAAgrIAbAAIAAArIA5AAIAAAbIg1AAQAKAaAOAUQAQAZAVARIgQAeQgVgUgTggIgJgQIAABdgAhOBrIAAhvIgPAVIgPgbQAggsAPg0IAbAIQgHAZgKATIAAChg");
	this.shape_5.setTransform(93.7,10.875);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAMBqQgJAAgGgCQgRgBAAgYIAAgEIgvAAIAAAKIgaAAIAAhWICtAAIAABMIhKAAQACAHADAAQABABAJAAIAngBIAPgBQAIAAADgPIAWALQgEARgJAHQgHADgLABIg4ABgAAGA0IAxAAIAAgGIgxAAgAhDA0IAvAAIAAgGIgvAAgAAGAaIAxAAIAAgGIgxAAgAhDAaIAvAAIAAgGIgvAAgAANgGIAAgUIA6AAIAAAUgAhPgGIAAgUIA5AAIAAAUgAgRgJIAAguIhCAAIAAAWIgZAAIAAguIBbAAIAAgEIhKAAIAAgWICwAAIAAAWIhMAAIAAAEIBcAAIAAAuIgZAAIAAgWIhDAAIAAAugAANgeIAAgUIA6AAIAAAUgAhPgeIAAgUIA5AAIAAAUg");
	this.shape_6.setTransform(52.6,10.925);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhHBsIAAhbIgdAFIgFgaIAMgBIASgWIgfgYIAOgSIAEADQAOgaAGgPIAYAKQgLAWgOAWIAJAGQAKgNAKgRIAYALQgcAlgSAUIAUgCIgDgNIAWgGQAHATAEAUIAAgrIAZAAIAAAzIAPAAIAAhIIgqAAIAAgZIAqAAIAAgZIAbAAIAAAZIAuAAIAAAZIguAAIAABIIAPAAIAAg0IAbAAIAABMIgqAAIAAAbQAAAJAEAAQABABAIAAQAJAAABgCQADgBAAgGIACgLIAZAOQgEAYgIAEQgCADgIAAIgSABQgLAAgKgCQgTgDAAgZIAAghIgPAAIAAALIgYAAIAFAUIgYAHQgFgZgHgTIAVgHIAJAVIAAgiIgYAHIgBgKIgJABIAABfgAhrBQQAHgdACgWIAXAGQgEAfgFAVg");
	this.shape_7.setTransform(10.825,10.825);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},14).to({state:[]},1).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},5).wait(25));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336.7,21.8);


(lib.sb_line = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_4
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(0.5,1,1).p("A7OAAMA2dAAA");
	this.shape.setTransform(175.25,1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,350.5,2);


(lib.sb_car1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// car
	this.instance = new lib.car1();
	this.instance.setTransform(0,0,1.0535,1.0537);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,473,259.2);


(lib.sb_bg1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#0C0F08","rgba(69,91,44,0)"],[0.325,1],-1220,-0.1,1219.9,-0.1).s().p("Ei+nAs/MAAAhZ9MF9PAAAMAAABZ9g");
	this.shape.setTransform(2139.6677,194.9012,0.902,2.3538,-168.3118);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#070A05","rgba(69,91,44,0)"],[0.145,1],-1220,-0.1,1219.9,-0.1).s().p("Ei+nAs/MAAAhZ9MF9PAAAMAAABZ9g");
	this.shape_1.setTransform(-1208.5677,151.8488,0.902,2.3538,11.6882);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(47));

	// bg1
	this.instance = new lib.bg1();
	this.instance.setTransform(-2570,-13,2.9526,2.9526);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(47));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-2570,-734.6,5924.6,1816);


(lib.sb_ariya = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AR/DWIgvhNIlPAAIgvBNIhfAAIEMmrIBaAAIDcFaIAOASQAPAVAKAFQATANA0gBIAEAZgAQnBCIh8jQIh+DQID6AAgAFtDWIAAiZIkLkSIBwAAIDEDLIDMjLIBtAAIkLESIAACZgAhEDWIAAmrIBTAAIAAGrgAlEDWIiUinIhhAAIgthHIAAAAIC3AAIAxgBQAagCAMgJQANgJAEgUQAGgUgHgTQgIgYgbgHQgQgDgvAAIkGAAIgthLIEbAAQBEAAATABQArAEAZAOQAoAYAMA9QAMA9geAsQgRAagbAMQgXALgpADICWCmgArcDWIguhNIlPAAIgwBNIidAAIAFgaQAcAAAOgCQAVgCAMgIQANgLAVggIDXlaIBdAAIEOGrgAs0BCIh7jQIh9DQID4AAg");
	this.shape.setTransform(131.9,21.45);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,263.8,42.9);


(lib.mo_logo = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// logo
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AA8BXIiBiBIAACBIgmAAIAAitIAxAAICACBIAAiBIAmAAIAACtg");
	this.shape.setTransform(138.825,62.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhpBXIAAgkICiAAQAPgDAAgOQAAgPgQgDIhqAAIgRgBQgUgDgMgPQgLgOAAgRQAAgVANgNQAMgOATgDIAPgBICWAAIAAAkIiTAAQgJAAgCAAQgMAEAAAMQAAAMAMACIALABIBzABQAUACANAQQALAOAAATQAAAVgLAOQgNARgXACg");
	this.shape_1.setTransform(52.625,62.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhpBXIAAgkICiAAQAPgDAAgOQAAgPgQgDIhrAAIgQgBQgUgDgMgPQgLgOAAgRQAAgVANgNQAMgOATgDIAPgBICWAAIAAAkIiUAAQgIAAgDAAQgLAEAAAMQAAAMALACIAMABIByABQAVACAMAQQAMAOAAATQAAAVgMAOQgNARgWACg");
	this.shape_2.setTransform(81.55,62.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("ABSBXIgTgfIh+AAIgTAfIguAAIBsitIAoAAIBtCtgAAsAXIgshFIgrBFIBXAAg");
	this.shape_3.setTransform(110,62.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AA7BXIiAiBIAACBIgmAAIAAitIAxAAICACBIAAiBIAmAAIAACtg");
	this.shape_4.setTransform(10.825,62.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgSBXIAAitIAlAAIAACtg");
	this.shape_5.setTransform(32.075,62.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AlPB7QiahihMiiIgEgGQgLgXgJgIQgOgOgegDIhHgIIAAgVICqAAIABACQA6CqCTBoQCUBpC0AAQC1AACThpQCUhoA6iqIABgCICqAAIAAAVIhHAIQgdADgPAOQgJAJgLAWIgEAGQhMCiiaBjQibBhi1AAQi0AAibhig");
	this.shape_6.setTransform(74.85,103.15);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AIXDdIgBgCQg6iqiUhoQiThpi1AAQi0AAiUBpQiTBog6CqIgBACIiqAAIAAgUIBHgJQAegDAOgOQAKgJAKgWIAEgGQBMijCahhQCbhiC0AAQC1AACbBiQCaBhBMCjIAEAGQALAWAJAJQAPAOAdADIBHAJIAAAUg");
	this.shape_7.setTransform(74.85,22.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(450));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,149.7,125.3);


(lib.sb_sc3tt = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// mo_sc3_tt
	this.instance = new lib.mo_sc3tt();
	this.instance.setTransform(261.6,13.8,1,1,0,0,0,261.6,13.8);
	this.instance.shadow = new cjs.Shadow("rgba(96,51,23,1)",0,0,7);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-8,-8,543,47);


(lib.sb_btnbg = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// _Path_
	this.instance = new lib.Path();
	this.instance.setTransform(94.6,19.7,1,1,0,0,0,94.6,19.7);
	this.instance.compositeOperation = "hard-light";

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(5).to({_off:true},1).wait(2).to({_off:false},0).wait(39));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,189.2,39.5);


(lib.an_sc3tt = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// sb_sc3_tt
	this.instance = new lib.sb_sc3tt("synched",0);
	this.instance.setTransform(269.6,21.8,1,1,0,0,0,261.6,13.8);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:1},8).wait(35));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,543,47);


(lib.an_btn = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// sb_btn_t
	this.instance = new lib.sb_btnt("synched",0);
	this.instance.setTransform(94.65,19.6,1.2098,1.2098,0,0,0,66.3,10);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regX:66.2,scaleX:1,scaleY:1,x:94.5,y:19.55,alpha:1,startPosition:8},6).wait(39));

	// sb_btn_bg
	this.instance_1 = new lib.sb_btnbg("synched",0);
	this.instance_1.setTransform(94.45,19.7,1.3203,1.3203,0,0,0,94.5,19.7);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({regX:94.6,scaleX:1,scaleY:1,x:94.6,alpha:1,startPosition:8},6).wait(39));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-30.3,-6.3,249.8,52.099999999999994);


(lib.sb_ccc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// mo_ccc
	this.instance = new lib.mo_ccc();
	this.instance.setTransform(92.2,92.2,1,1,0,0,0,92.2,92.2);
	this.instance.compositeOperation = "overlay";

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(50));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,184.4,184.4);


(lib.an_sc2title = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// sb_sc2_title
	this.instance = new lib.sb_sc2title("synched",0);
	this.instance.setTransform(115.7,17,1,1,0,0,0,115.7,17);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:27,alpha:1},13,cjs.Ease.cubicOut).wait(37));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,231.5,44);


(lib.an_sc2if = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// sb_sc2_if
	this.instance = new lib.sb_sc2if("synched",0);
	this.instance.setTransform(206.9,10.8,1,1,0,0,0,206.9,10.8);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:1},13).wait(37));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,413.9,21.8);


(lib.an_sc2bg = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// sb_sc2_t_bg
	this.instance = new lib.sb_sc2tbg("synched",0);
	this.instance.setTransform(300,46.2,0.1902,1,0,0,0,300,46.1);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regY:46,scaleX:1,y:46.1,alpha:1},13).wait(37));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0.1,600,92.10000000000001);


(lib.an_start = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// sb_start
	this.instance = new lib.sb_start("synched",0);
	this.instance.setTransform(168.3,10.8,1,1,0,0,0,168.3,10.8);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:1,startPosition:20},15).wait(30));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336.7,21.8);


(lib.an_line = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// sb_line
	this.instance = new lib.sb_line("synched",0);
	this.instance.setTransform(175.25,1,0.0158,1,0,0,0,174.3,1);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regX:175.2,scaleX:1,x:175.2,alpha:1},9).wait(36));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,350.5,2);


(lib.an_car1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// sb_car1
	this.instance = new lib.sb_car1("synched",0);
	this.instance.setTransform(447,143.5,1,1,0,0,0,236.5,129.7);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:236.5,y:151.05,alpha:1},13,cjs.Ease.cubicOut).wait(32));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,13.8,683.5,266.8);


(lib.an_bg1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// sb_bg1
	this.instance = new lib.sb_bg1("synched",0);
	this.instance.setTransform(308.15,256.8,1.0275,1.0275,0,0,0,299.9,249.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regY:250,scaleX:1.0042,scaleY:1.0042,startPosition:46},32).wait(54));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-2640.7,-754.8,6087.6,1865.8999999999999);


(lib.an_ariya = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// sb_ariya
	this.instance = new lib.sb_ariya("synched",0);
	this.instance.setTransform(131.9,21.4,1,1,0,0,0,131.9,21.4);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:29.4,alpha:1},23,cjs.Ease.cubicOut).wait(22));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,263.8,50.9);


(lib.an_car2sharp = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("A3NK0QADhfgJhPQgLhhgYg8QgihWhCgkQhTgvhVAjQhMAeg3BSQgJANgJARQAeijBLhNQAggiA/gqQCAhTCggoQgNgIgJgQQgSggATgjQAJgRAWgPQAsgdA9AOIAIAIQAHAJAAALQAAADAigfQA1gxAzgpQDBiWDwhcIBRgcQBtgiCJgZQG3hTIzAYIBwAFQCJAIB7APQGHAvBgBeIAGAWQABAZgYAPIBvAmQBvArAFAbIAfAEQAkAHAfAMQBhAlACBFIAKAwQAHA4gRAsIBhE9IAFBSQAEBXgHAfIgDA8QgGBDgQAkQgUgCgUAIQgpAPg0ACIkIgbQicgQhsgHQj6gQjTATQjgAXhxAHQAmipgsiCQgyiXiHhXQiRhdiRA0QhOAHhFA2QhEA1ggBLQg9CNgCCHQgBAoAEA1IAHBcQgtgTg5gMQirgninAPIrIA7g");
	mask.setTransform(194.4363,69.2145);

	// sb_ccc_copy
	this.instance = new lib.sb_ccc("synched",0);
	this.instance.setTransform(299.25,36.6,2.3594,3.5524,16.9618,0,0,92.2,92);
	this.instance._off = true;

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(30).to({_off:false},0).to({regX:92.1,scaleX:3.4189,scaleY:5.1477,rotation:16.9615,x:621.35,y:94.7,alpha:0.5898,startPosition:12},28,cjs.Ease.cubicOut).wait(33));

	// sb_ccc
	this.instance_1 = new lib.sb_ccc("synched",0);
	this.instance_1.setTransform(72.85,0.35,2.3594,3.5524,16.9618,0,0,92.2,92);
	this.instance_1._off = true;

	var maskedShapeInstanceList = [this.instance_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(30).to({_off:false},0).to({regX:92.1,scaleX:3.4189,scaleY:5.1477,rotation:16.9615,x:-169.1,y:-166.7,alpha:0.5898,startPosition:12},28,cjs.Ease.cubicOut).wait(33));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,388.9,138.5);


(lib.an_car1sharp = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// sb_car1_sharp (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_25 = new cjs.Graphics().p("A1BUWQgqgNgzgwQhkhggoizQgQgqgRhOQgjidgJi1IgGAiQgIAlgSAJQgWAKggAIQg+AQgvgMQgMgDgNgSQgZgjgFhJQgJg/gKhYQgTixgDiAQgQgZgJhFQgQiMApjcQACgXAPggQAehAA/grQgcAEgigEQhDgIgagsQgJgRgFgXQgJgtAXgaQAQgVAmgXQBMgvBvgKQAJg4AghIQBBiNB0hKQCQglEHggQIPg9JTAfIBKADQBOAGAbATICxBQQDNBiCEBaIAXgFQAcgDAdADQBcALA7BFIBKgNQBhgKB3AQICBApQCXA4BxBLIArAxQAqA6gBAmIAfAdQAmAqAjBDQBuDWAhF4IAZAlQAcA0ALBEQALBEgKBHQgGAkgHAWQgWArgpAsQhRBYhdAIQggArgrAvQhVBfg5AYIkAA1QgcAIgngDQhPgFg7gyQjOAklOAwQqaBfp9A7IghBAQgwBFhJAdQghAShGANQhVARhlAAQhAAAhHgHg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(25).to({graphics:mask_graphics_25,x:200.8698,y:130.8554}).wait(66));

	// sb_ccc_copy
	this.instance = new lib.sb_ccc("synched",0);
	this.instance.setTransform(280.4,148.05,2.3594,3.5524,16.9618,0,0,92.2,92);
	this.instance._off = true;

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(25).to({_off:false},0).to({regX:92.1,scaleX:3.4189,scaleY:5.1477,rotation:16.9615,x:602.5,y:206.15,alpha:0.5898,startPosition:12},24,cjs.Ease.cubicOut).wait(42));

	// sb_ccc
	this.instance_1 = new lib.sb_ccc("synched",0);
	this.instance_1.setTransform(74,111.8,2.3594,3.5524,16.9618,0,0,92.2,92);
	this.instance_1._off = true;

	var maskedShapeInstanceList = [this.instance_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(25).to({_off:false},0).to({regX:92.1,scaleX:3.4189,scaleY:5.1477,rotation:16.9615,x:-187.95,y:-55.25,alpha:0.5898,startPosition:12},24,cjs.Ease.cubicOut).wait(42));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,401.8,261.7);


(lib.sc3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// an_btn
	this.instance = new lib.an_btn("synched",0,false);
	this.instance.setTransform(1949.9,439.35,3.1235,3.1235,0,0,0,94.4,19.8);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(11).to({_off:false},0).wait(80));

	// an_sc3_tt
	this.instance_1 = new lib.an_sc3tt("synched",0,false);
	this.instance_1.setTransform(-361.1,368,2.701,2.701,0,0,0,271.4,24);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(2).to({_off:false},0).wait(89));

	// an_ariya
	this.instance_2 = new lib.an_ariya("synched",0,false);
	this.instance_2.setTransform(-381.7,180.15,3.2058,3.2058,0,0,0,131.9,25.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(91));

	// an_car2_sharp
	this.instance_3 = new lib.an_car2sharp("synched",0,false);
	this.instance_3.setTransform(966.3,213.4,2.3772,2.3772,0,0,0,194.5,69.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(91));

	// sb_ccc_copy_copy
	this.instance_4 = new lib.sb_ccc("synched",12);
	this.instance_4.setTransform(1126.25,226.15,0.8382,1.7659,16.9613,0,0,92.2,91.9);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(36).to({_off:false},0).to({regX:92,regY:91.7,scaleX:19.744,scaleY:34.6603,rotation:16.9614,x:1140.4,y:258.55,alpha:0.3398},15).to({regX:91.8,regY:91.6,scaleX:87.9779,scaleY:154.444,x:1138.5,y:260,alpha:0},8).wait(32));

	// sb_sc3_bg
	this.instance_5 = new lib.sb_sc3bg("synched",0);
	this.instance_5.setTransform(300,250,1,1,0,0,0,300,250);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(91));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-7680.3,-13485.8,17650.9,27689.6);


(lib.sc2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// an_sc2_title
	this.instance = new lib.an_sc2title("synched",0,false);
	this.instance.setTransform(-294.4,186.85,3.4498,3.4498,0,0,0,115.7,22.1);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(4).to({_off:false},0).wait(87));

	// an_sc2_if
	this.instance_1 = new lib.an_sc2if("synched",0,false);
	this.instance_1.setTransform(-297.8,345,3.8906,3.8906,0,0,0,206.8,11);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(4).to({_off:false},0).wait(87));

	// an_sc2_bg
	this.instance_2 = new lib.an_sc2bg("synched",0,false);
	this.instance_2.setTransform(-1237.2,89.3,3.0542,3.7354,0,0,0,-0.2,0.1);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(4).to({_off:false},0).wait(87));

	// an_car1_sharp
	this.instance_3 = new lib.an_car1sharp("synched",0,false);
	this.instance_3.setTransform(987.85,262.6,1.8548,1.8548,0,0,0,189.5,130.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(91));

	// sb_bg2
	this.instance_4 = new lib.sb_bg2("synched",0);
	this.instance_4.setTransform(300.05,250,1.0278,1.0278,0,0,0,300,250);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({regX:299.9,scaleX:1.009,scaleY:1.009,x:299.9},26).wait(65));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-2629.7,-1284.2,6029.799999999999,2867.5);


(lib.sc1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// an_ariya
	this.instance = new lib.an_ariya("synched",0,false);
	this.instance.setTransform(694.15,147.1,2.8107,2.8107,0,0,0,131.9,25.6);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(12).to({_off:false},0).wait(83));

	// an_line_copy
	this.instance_1 = new lib.an_line("synched",0,false);
	this.instance_1.setTransform(693.9,413.35,3.9836,3.9836,0,0,0,175.2,1.1);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(4).to({_off:false},0).wait(91));

	// an_line
	this.instance_2 = new lib.an_line("synched",0,false);
	this.instance_2.setTransform(693.9,266.4,3.9836,3.9836,0,0,0,175.2,1.1);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(6).to({_off:false},0).wait(89));

	// an_start
	this.instance_3 = new lib.an_start("synched",0,false);
	this.instance_3.setTransform(694.35,339.3,4.0226,4.0226,0,0,0,168.4,10.9);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(4).to({_off:false},0).wait(91));

	// an_car1
	this.instance_4 = new lib.an_car1("synched",0,false);
	this.instance_4.setTransform(21.55,311.65,2.3066,2.3066,0,0,0,507.2,140.2);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(8).to({_off:false},0).wait(87));

	// an_bg1
	this.instance_5 = new lib.an_bg1("synched",0,false);
	this.instance_5.setTransform(300,250.15,1,1,0,0,0,308.2,256.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(95));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-2648.9,-761.5,6087.6,1865.9);


(lib.wrap = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// mo_logo
	this.instance = new lib.mo_logo();
	this.instance.setTransform(-328.8,2179.1,2.6328,2.6337,0,0,0,74.9,62.8);
	this.instance.shadow = new cjs.Shadow("rgba(0,0,0,0.698)",0,3,9);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(360));

	// sc3
	this.instance_1 = new lib.sc3("synched",0,false);
	this.instance_1.setTransform(1399.95,2182.2,1,1,0,0,0,300,250.8);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(240).to({_off:false},0).wait(120));

	// sc2
	this.instance_2 = new lib.sc2("synched",0,false);
	this.instance_2.setTransform(1399.95,2182.15,1,1,0,0,0,300,250);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(120).to({_off:false},0).to({_off:true},120).wait(120));

	// sc1
	this.instance_3 = new lib.sc1("synched",0,false);
	this.instance_3.setTransform(1401.9,2183.15,1,1,0,0,0,300,250);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({_off:true},120).wait(240));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-6580.4,-11554.4,17650.9,27689.6);


// stage content:
(lib._320x50 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = false; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// wrap
	this.instance = new lib.wrap("synched",0);
	this.instance.setTransform(202.35,26.85,0.1,0.1,0,0,0,1403.2,2200.7);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(719).to({y:26.8,mode:"single",startPosition:359},0).wait(1));

	// stageBackground
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("rgba(0,0,0,0)").ss(1,1,1,3,true).p("A6jldMA1HAAAIAAK7Mg1HAAAg");
	this.shape.setTransform(160,25);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("A6jFeIAAq7MA1HAAAIAAK7g");
	this.shape_1.setTransform(160,25);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(720));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(-435.9,-1323.4,1605,2743.7);
// library properties:
lib.properties = {
	id: '8E6E2E7554C041E6B394D1A9E196CBFB',
	width: 320,
	height: 50,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/bg1.jpg", id:"bg1"},
		{src:"images/bg2.jpg", id:"bg2"},
		{src:"images/bg3.jpg", id:"bg3"},
		{src:"images/car1.png", id:"car1"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['8E6E2E7554C041E6B394D1A9E196CBFB'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;